[package]
name = "arut-runtime-local"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arut-storage.workspace = true
arut-transport-ipc.workspace = true
arut-transport-connect-http.workspace = true
arut-product-session.workspace = true
arut-feature-chat.workspace = true
arut-protocol.workspace = true
arut-rpc.workspace = true
axum = "0.8.4"
prost = "0.14.1"
tokio = { version = "1.47.1", features = ["macros", "net", "rt-multi-thread", "signal", "process", "io-util"] }
tower-http = { version = "0.6.6", features = ["cors"] }

[dev-dependencies]
futures-util = "0.3.31"
arut-transport-connect-http.workspace = true

[[bin]]
name = "arutd"
path = "src/main.rs"
