[package]
name = "arut-backend-composer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arut-feature-chat.workspace = true
arut-protocol.workspace = true
arut-rpc.workspace = true
axum = "0.8.4"
prost = "0.14.1"
tokio = { version = "1.47.1", features = ["macros", "net", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6.6", features = ["cors"] }

[dev-dependencies]
arut-transport-http.workspace = true
