using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Arut.Surface.Windows;

/// <summary>
/// One conversation's projections. Every property is generated by the MVVM
/// Toolkit; the only hand-written code is one pump per generated stream, which
/// reads the projection Rust just revised (ADR 0021).
/// </summary>
public sealed partial class ConversationViewModel : ObservableObject, IAsyncDisposable
{
    private readonly ChatHandle chat;
    private readonly ComposerHandle composer;
    private readonly CancellationTokenSource lifetime = new();
    private Task running = Task.CompletedTask;
    private bool echoing;
    private bool disposed;

    public ConversationViewModel(ChatHandle chat)
    {
        this.chat = chat;
        composer = chat.Composer();
        State = chat.State();
        Draft = composer.State().Text;
        Error = "";
    }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsSending), nameof(IsIdle), nameof(IsEmpty))]
    [NotifyCanExecuteChangedFor(nameof(SendCommand))]
    public partial ChatState State { get; set; }

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SendCommand))]
    public partial string Draft { get; set; }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasError))]
    public partial string Error { get; set; }

    public ObservableCollection<MessageRow> Messages { get; } = [];
    public string? Id => State.Id;
    public bool IsSending => State.IsSending;
    public bool IsIdle => !State.IsSending;
    public bool IsEmpty => Messages.Count == 0;
    public bool HasError => Error.Length > 0;

    /// <summary>Starts the observation pumps on the caller's context, which in
    /// this app is the UI thread, so every projection read lands there too.</summary>
    public void Start() => running = RunAsync();

    private async Task RunAsync()
    {
        Refresh();
        try
        {
            await Task.WhenAll(
                FollowAsync(),
                Pump(chat.ChatChanges(lifetime.Token), RefreshTranscript),
                Pump(composer.ComposerChanges(lifetime.Token), RefreshDraft)
            );
        }
        catch (OperationCanceledException) when (lifetime.IsCancellationRequested) { }
        catch (Exception exception)
        {
            System.Diagnostics.Trace.TraceError(exception.ToString());
            if (!disposed)
                Error = L10n.Get(L10n.NodeFailureInternal);
        }
    }

    private static async Task Pump(IAsyncEnumerable<ulong> revisions, Action apply)
    {
        await foreach (var _ in revisions)
            apply();
    }

    private async Task FollowAsync()
    {
        await composer.Initialize(lifetime.Token);
        await composer.Follow(lifetime.Token);
    }

    // Local echo, then the write. Rust coalesces rapid edits behind one
    // in-flight request and keeps the last, so there is no queue here.
    partial void OnDraftChanged(string value)
    {
        if (echoing || disposed)
            return;
        _ = ReplaceAsync(value);
    }

    private async Task ReplaceAsync(string value)
    {
        try
        {
            await composer.Replace(value, lifetime.Token);
        }
        catch (OperationCanceledException) when (lifetime.IsCancellationRequested) { }
        catch (Exception exception)
        {
            System.Diagnostics.Trace.TraceError(exception.ToString());
            Error = L10n.Get(L10n.NodeFailureInternal);
        }
    }

    [RelayCommand(CanExecute = nameof(CanSend))]
    private async Task SendAsync()
    {
        var text = Draft;
        try
        {
            await chat.Send(text, lifetime.Token);
        }
        catch (OperationCanceledException) when (lifetime.IsCancellationRequested) { }
        catch (Exception exception)
        {
            System.Diagnostics.Trace.TraceError(exception.ToString());
            Error = L10n.Get(L10n.NodeFailureInternal);
        }
    }

    private bool CanSend() => State.CanSend && !string.IsNullOrWhiteSpace(Draft);

    private void Refresh()
    {
        RefreshTranscript();
        RefreshDraft();
    }

    private void RefreshTranscript()
    {
        if (disposed)
            return;
        State = chat.State();
        var cursor = Messages.Count == 0 ? 0UL : Messages[^1].Id;
        var before = Messages.Count;
        foreach (var message in chat.MessagesAfter(cursor))
            Messages.Add(MessageRow.From(message));
        if (before != Messages.Count)
            OnPropertyChanged(nameof(IsEmpty));
        RefreshError();
    }

    private void RefreshDraft()
    {
        if (disposed)
            return;
        var text = composer.State().Text;
        if (text != Draft)
        {
            echoing = true;
            Draft = text;
            echoing = false;
        }
        RefreshError();
    }

    // The chat's own error wins; a composer-only failure still has to reach the
    // person when the chat itself is idle.
    private void RefreshError() =>
        Error = chat.ErrorKey() is { } key
            ? Strings.Describe(key, chat.ErrorArgs())
            : Strings.Describe(composer.ErrorKey(), composer.ErrorArgs());

    public async ValueTask DisposeAsync()
    {
        if (disposed)
            return;
        disposed = true;
        lifetime.Cancel();
        try
        {
            await running;
        }
        catch (OperationCanceledException) { }
        composer.Dispose();
        chat.Dispose();
        lifetime.Dispose();
    }
}
