using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Arut.Surface.Windows;

/// <summary>
/// One conversation's projections. Every property is generated by the MVVM
/// Toolkit and every read of a revision comes from <c>Arut.Bindings</c>; what is
/// left here is this screen's own rule -- which of the two scopes' errors it
/// shows -- and the intents (ADR 0021).
/// </summary>
public sealed partial class ConversationViewModel : ObservableObject, IAsyncDisposable
{
    private readonly ChatHandle chat;
    private readonly ComposerHandle composer;
    private readonly CancellationTokenSource lifetime = new();
    private readonly Projection<ChatState> state;
    private readonly Projection<ComposerState> composerState;
    private Task following = Task.CompletedTask;
    private bool disposed;

    public ConversationViewModel(ChatHandle chat)
    {
        this.chat = chat;
        composer = chat.Composer();
        state = new Projection<ChatState>(chat.State, chat.ChatChanges);
        composerState = new Projection<ComposerState>(composer.State, composer.ComposerChanges);
        Messages = new Rows<MessageRow>(
            row => row.Id,
            cursor => [.. chat.MessagesAfter(cursor).Select(MessageRow.From)]
        );
        Draft = new Draft(composer.State().Text, text => composer.Replace(text, lifetime.Token))
        {
            Faulted = Report,
        };
        Error = "";
        Draft.PropertyChanged += (_, _) => SendCommand.NotifyCanExecuteChanged();
        state.PropertyChanged += (_, _) => ChatRevised();
        composerState.PropertyChanged += (_, _) => ComposerRevised();
        Messages.CollectionChanged += (_, _) => OnPropertyChanged(nameof(IsEmpty));
    }

    public Rows<MessageRow> Messages { get; }
    public Draft Draft { get; }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasError))]
    public partial string Error { get; set; }

    public ChatState State => state.Value;
    public string? Id => State.Id;
    public bool IsSending => State.IsSending;
    public bool IsIdle => !State.IsSending;
    public bool IsEmpty => Messages.Count == 0;
    public bool HasError => Error.Length > 0;

    /// <summary>Starts the pumps on the caller's context, which in this app is
    /// the UI thread, so every projection read lands there too.</summary>
    public void Start()
    {
        state.Start();
        composerState.Start();
        following = Following.RunAsync(composer.Initialize, composer.Follow, lifetime.Token);
        ChatRevised();
        ComposerRevised();
    }

    [RelayCommand(CanExecute = nameof(CanSend))]
    private async Task SendAsync()
    {
        var text = Draft.Text;
        try
        {
            await chat.Send(text, lifetime.Token);
        }
        catch (OperationCanceledException) when (lifetime.IsCancellationRequested) { }
        catch (Exception exception)
        {
            Report(exception);
        }
    }

    private bool CanSend() => State.CanSend && !string.IsNullOrWhiteSpace(Draft.Text);

    private void ChatRevised()
    {
        if (disposed)
            return;
        Messages.Refresh();
        OnPropertyChanged(nameof(State));
        OnPropertyChanged(nameof(IsSending));
        OnPropertyChanged(nameof(IsIdle));
        SendCommand.NotifyCanExecuteChanged();
        RefreshError();
    }

    private void ComposerRevised()
    {
        if (disposed)
            return;
        Draft.Absorb(composerState.Value.Text);
        SendCommand.NotifyCanExecuteChanged();
        RefreshError();
    }

    // The chat's own error wins; a composer-only failure still has to reach the
    // person when the chat itself is idle.
    private void RefreshError() =>
        Error = chat.ErrorKey() is { } key
            ? ErrorText.Describe(key, chat.ErrorArgs(), Lookup)
            : ErrorText.Describe(composer.ErrorKey(), composer.ErrorArgs(), Lookup);

    // `L10n.Get` takes format arguments as well, so it needs naming as the
    // one-argument lookup `ErrorText` asks for.
    private static string Lookup(string name) => L10n.Get(name);

    /// <summary>A thrown call is a transport failure, not a typed outcome; typed
    /// outcomes arrive through <c>ErrorKey()</c> on the next revision.</summary>
    private void Report(Exception exception)
    {
        System.Diagnostics.Trace.TraceError(exception.ToString());
        if (!disposed)
            Error = L10n.Get(L10n.NodeFailureInternal);
    }

    public async ValueTask DisposeAsync()
    {
        if (disposed)
            return;
        disposed = true;
        lifetime.Cancel();
        await state.DisposeAsync();
        await composerState.DisposeAsync();
        try
        {
            await following;
        }
        catch (OperationCanceledException) { }
        composer.Dispose();
        chat.Dispose();
        lifetime.Dispose();
    }
}
