[package]
name = "arut-rpc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures-core = "0.3.31"
futures-util = "0.3.31"
prost = "0.14.1"
tracing = "0.1.44"
tokio-util = { version = "0.7.19", default-features = false }

[lints]
workspace = true

[dev-dependencies]
futures-executor = "0.3.31"
