//! Generated by `mise run i18n` from product/i18n/locales. Do not edit.
//!
//! One variant per message in `locales/en/*.ftl`, carrying that message's
//! Fluent arguments with the types the source declares. A key is never
//! written by hand: [`Localizer::format`] takes a `Message`, so a message
//! that does not exist, or an argument of the wrong type, does not compile.

use crate::{FluentArgs, FluentValue};

/// Every string the product can show.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum Message {
    /// `action-close-history`
    ActionCloseHistory,
    /// `action-collapse-sidebar`
    ActionCollapseSidebar,
    /// `action-copy-message`
    ActionCopyMessage,
    /// `action-expand-sidebar`
    ActionExpandSidebar,
    /// `action-focus-composer`
    ActionFocusComposer,
    /// `action-new-chat`
    ActionNewChat,
    /// `action-new-chat-shortcut`
    ActionNewChatShortcut { shortcut: String },
    /// `action-new-conversation`
    ActionNewConversation,
    /// `action-new-conversation-shortcut`
    ActionNewConversationShortcut { shortcut: String },
    /// `action-next-conversation`
    ActionNextConversation,
    /// `action-open-history`
    ActionOpenHistory,
    /// `action-previous-conversation`
    ActionPreviousConversation,
    /// `action-scroll-to-latest`
    ActionScrollToLatest,
    /// `action-search-conversations`
    ActionSearchConversations,
    /// `action-send`
    ActionSend,
    /// `action-send-message`
    ActionSendMessage,
    /// `action-toggle-history`
    ActionToggleHistory,
    /// `action-toggle-history-shortcut`
    ActionToggleHistoryShortcut { shortcut: String },
    /// `action-toggle-sidebar`
    ActionToggleSidebar,
    /// `action-toggle-sidebar-shortcut`
    ActionToggleSidebarShortcut { shortcut: String },
    /// `app-name`
    AppName,
    /// `availability-available`
    AvailabilityAvailable,
    /// `availability-manifest-unreachable`
    AvailabilityManifestUnreachable,
    /// `availability-not-advertised`
    AvailabilityNotAdvertised,
    /// `availability-reported-unavailable`
    AvailabilityReportedUnavailable,
    /// `availability-unknown`
    AvailabilityUnknown,
    /// `chat-draft-synced`
    ChatDraftSynced,
    /// `chat-empty-hint`
    ChatEmptyHint,
    /// `chat-empty-start`
    ChatEmptyStart,
    /// `chat-empty-title`
    ChatEmptyTitle,
    /// `chat-error-cancelled`
    ChatErrorCancelled,
    /// `chat-error-chat-id-missing`
    ChatErrorChatIdMissing,
    /// `chat-error-no-conversation`
    ChatErrorNoConversation,
    /// `chat-history-empty`
    ChatHistoryEmpty,
    /// `chat-local-session`
    ChatLocalSession,
    /// `chat-role-assistant`
    ChatRoleAssistant,
    /// `chat-role-you`
    ChatRoleYou,
    /// `chat-session-saved`
    ChatSessionSaved,
    /// `chat-status-failed`
    ChatStatusFailed,
    /// `chat-status-sending`
    ChatStatusSending,
    /// `chat-status-thinking`
    ChatStatusThinking,
    /// `composer-error-authority-changed`
    ComposerErrorAuthorityChanged { current_epoch: String },
    /// `composer-error-outcome-missing`
    ComposerErrorOutcomeMissing,
    /// `composer-error-revision-conflict`
    ComposerErrorRevisionConflict { current: String },
    /// `composer-error-scope-mismatch`
    ComposerErrorScopeMismatch,
    /// `composer-error-scope-missing`
    ComposerErrorScopeMissing,
    /// `composer-error-snapshot-missing`
    ComposerErrorSnapshotMissing,
    /// `composer-hint-command-return`
    ComposerHintCommandReturn,
    /// `composer-hint-enter`
    ComposerHintEnter,
    /// `composer-hint-multiline`
    ComposerHintMultiline,
    /// `composer-hint-option-return`
    ComposerHintOptionReturn,
    /// `composer-placeholder`
    ComposerPlaceholder,
    /// `composer-status-connecting`
    ComposerStatusConnecting,
    /// `composer-status-failed`
    ComposerStatusFailed,
    /// `conversation-search-empty`
    ConversationSearchEmpty,
    /// `conversation-search-placeholder`
    ConversationSearchPlaceholder,
    /// `label-chat-history`
    LabelChatHistory,
    /// `label-conversations`
    LabelConversations,
    /// `label-draft`
    LabelDraft,
    /// `label-draft-sync`
    LabelDraftSync,
    /// `label-message-status`
    LabelMessageStatus,
    /// `label-node-availability`
    LabelNodeAvailability,
    /// `label-recent`
    LabelRecent,
    /// `label-transcript`
    LabelTranscript,
    /// `label-unread-messages`
    LabelUnreadMessages,
    /// `node-failure-cancelled`
    NodeFailureCancelled,
    /// `node-failure-conflict`
    NodeFailureConflict,
    /// `node-failure-internal`
    NodeFailureInternal,
    /// `node-failure-missing`
    NodeFailureMissing,
    /// `node-failure-overloaded`
    NodeFailureOverloaded,
    /// `node-failure-refused`
    NodeFailureRefused,
    /// `node-failure-rejected`
    NodeFailureRejected,
    /// `node-failure-timed-out`
    NodeFailureTimedOut,
    /// `node-failure-unreachable`
    NodeFailureUnreachable,
    /// `node-failure-unsupported`
    NodeFailureUnsupported,
    /// `node-startup-failure-lease-held`
    NodeStartupFailureLeaseHeld,
    /// `node-startup-failure-socket-unreachable`
    NodeStartupFailureSocketUnreachable,
    /// `node-startup-failure-spawn-failed`
    NodeStartupFailureSpawnFailed,
    /// `rpc-error-already-exists`
    RpcErrorAlreadyExists,
    /// `rpc-error-cancelled`
    RpcErrorCancelled,
    /// `rpc-error-changed`
    RpcErrorChanged,
    /// `rpc-error-denied`
    RpcErrorDenied,
    /// `rpc-error-exhausted`
    RpcErrorExhausted,
    /// `rpc-error-internal`
    RpcErrorInternal,
    /// `rpc-error-not-found`
    RpcErrorNotFound,
    /// `rpc-error-rejected`
    RpcErrorRejected,
    /// `rpc-error-timed-out`
    RpcErrorTimedOut,
    /// `rpc-error-unavailable`
    RpcErrorUnavailable,
    /// `rpc-error-unsupported`
    RpcErrorUnsupported,
}

impl Message {
    /// The Fluent message id this variant names.
    #[must_use]
    pub const fn key(&self) -> &'static str {
        match self {
            Self::ActionCloseHistory => "action-close-history",
            Self::ActionCollapseSidebar => "action-collapse-sidebar",
            Self::ActionCopyMessage => "action-copy-message",
            Self::ActionExpandSidebar => "action-expand-sidebar",
            Self::ActionFocusComposer => "action-focus-composer",
            Self::ActionNewChat => "action-new-chat",
            Self::ActionNewChatShortcut { .. } => "action-new-chat-shortcut",
            Self::ActionNewConversation => "action-new-conversation",
            Self::ActionNewConversationShortcut { .. } => "action-new-conversation-shortcut",
            Self::ActionNextConversation => "action-next-conversation",
            Self::ActionOpenHistory => "action-open-history",
            Self::ActionPreviousConversation => "action-previous-conversation",
            Self::ActionScrollToLatest => "action-scroll-to-latest",
            Self::ActionSearchConversations => "action-search-conversations",
            Self::ActionSend => "action-send",
            Self::ActionSendMessage => "action-send-message",
            Self::ActionToggleHistory => "action-toggle-history",
            Self::ActionToggleHistoryShortcut { .. } => "action-toggle-history-shortcut",
            Self::ActionToggleSidebar => "action-toggle-sidebar",
            Self::ActionToggleSidebarShortcut { .. } => "action-toggle-sidebar-shortcut",
            Self::AppName => "app-name",
            Self::AvailabilityAvailable => "availability-available",
            Self::AvailabilityManifestUnreachable => "availability-manifest-unreachable",
            Self::AvailabilityNotAdvertised => "availability-not-advertised",
            Self::AvailabilityReportedUnavailable => "availability-reported-unavailable",
            Self::AvailabilityUnknown => "availability-unknown",
            Self::ChatDraftSynced => "chat-draft-synced",
            Self::ChatEmptyHint => "chat-empty-hint",
            Self::ChatEmptyStart => "chat-empty-start",
            Self::ChatEmptyTitle => "chat-empty-title",
            Self::ChatErrorCancelled => "chat-error-cancelled",
            Self::ChatErrorChatIdMissing => "chat-error-chat-id-missing",
            Self::ChatErrorNoConversation => "chat-error-no-conversation",
            Self::ChatHistoryEmpty => "chat-history-empty",
            Self::ChatLocalSession => "chat-local-session",
            Self::ChatRoleAssistant => "chat-role-assistant",
            Self::ChatRoleYou => "chat-role-you",
            Self::ChatSessionSaved => "chat-session-saved",
            Self::ChatStatusFailed => "chat-status-failed",
            Self::ChatStatusSending => "chat-status-sending",
            Self::ChatStatusThinking => "chat-status-thinking",
            Self::ComposerErrorAuthorityChanged { .. } => "composer-error-authority-changed",
            Self::ComposerErrorOutcomeMissing => "composer-error-outcome-missing",
            Self::ComposerErrorRevisionConflict { .. } => "composer-error-revision-conflict",
            Self::ComposerErrorScopeMismatch => "composer-error-scope-mismatch",
            Self::ComposerErrorScopeMissing => "composer-error-scope-missing",
            Self::ComposerErrorSnapshotMissing => "composer-error-snapshot-missing",
            Self::ComposerHintCommandReturn => "composer-hint-command-return",
            Self::ComposerHintEnter => "composer-hint-enter",
            Self::ComposerHintMultiline => "composer-hint-multiline",
            Self::ComposerHintOptionReturn => "composer-hint-option-return",
            Self::ComposerPlaceholder => "composer-placeholder",
            Self::ComposerStatusConnecting => "composer-status-connecting",
            Self::ComposerStatusFailed => "composer-status-failed",
            Self::ConversationSearchEmpty => "conversation-search-empty",
            Self::ConversationSearchPlaceholder => "conversation-search-placeholder",
            Self::LabelChatHistory => "label-chat-history",
            Self::LabelConversations => "label-conversations",
            Self::LabelDraft => "label-draft",
            Self::LabelDraftSync => "label-draft-sync",
            Self::LabelMessageStatus => "label-message-status",
            Self::LabelNodeAvailability => "label-node-availability",
            Self::LabelRecent => "label-recent",
            Self::LabelTranscript => "label-transcript",
            Self::LabelUnreadMessages => "label-unread-messages",
            Self::NodeFailureCancelled => "node-failure-cancelled",
            Self::NodeFailureConflict => "node-failure-conflict",
            Self::NodeFailureInternal => "node-failure-internal",
            Self::NodeFailureMissing => "node-failure-missing",
            Self::NodeFailureOverloaded => "node-failure-overloaded",
            Self::NodeFailureRefused => "node-failure-refused",
            Self::NodeFailureRejected => "node-failure-rejected",
            Self::NodeFailureTimedOut => "node-failure-timed-out",
            Self::NodeFailureUnreachable => "node-failure-unreachable",
            Self::NodeFailureUnsupported => "node-failure-unsupported",
            Self::NodeStartupFailureLeaseHeld => "node-startup-failure-lease-held",
            Self::NodeStartupFailureSocketUnreachable => "node-startup-failure-socket-unreachable",
            Self::NodeStartupFailureSpawnFailed => "node-startup-failure-spawn-failed",
            Self::RpcErrorAlreadyExists => "rpc-error-already-exists",
            Self::RpcErrorCancelled => "rpc-error-cancelled",
            Self::RpcErrorChanged => "rpc-error-changed",
            Self::RpcErrorDenied => "rpc-error-denied",
            Self::RpcErrorExhausted => "rpc-error-exhausted",
            Self::RpcErrorInternal => "rpc-error-internal",
            Self::RpcErrorNotFound => "rpc-error-not-found",
            Self::RpcErrorRejected => "rpc-error-rejected",
            Self::RpcErrorTimedOut => "rpc-error-timed-out",
            Self::RpcErrorUnavailable => "rpc-error-unavailable",
            Self::RpcErrorUnsupported => "rpc-error-unsupported",
        }
    }

    /// The Fluent arguments this variant carries.
    #[must_use]
    pub fn args(&self) -> FluentArgs<'_> {
        let mut args = FluentArgs::new();
        match self {
            Self::ComposerErrorRevisionConflict { current } => {
                args.set("current", FluentValue::from(current.as_str()));
            }
            Self::ComposerErrorAuthorityChanged { current_epoch } => {
                args.set("currentEpoch", FluentValue::from(current_epoch.as_str()));
            }
            Self::ActionNewChatShortcut { shortcut }
            | Self::ActionNewConversationShortcut { shortcut }
            | Self::ActionToggleHistoryShortcut { shortcut }
            | Self::ActionToggleSidebarShortcut { shortcut } => {
                args.set("shortcut", FluentValue::from(shortcut.as_str()));
            }
            _ => {}
        }
        args
    }
}
