//! Generated by `mise run i18n` from product/i18n/locales. Do not edit.
//!
//! One variant per message in `locales/en/*.ftl`, carrying that message's
//! Fluent arguments with the types the source declares. A key is never
//! written by hand: [`Localizer::format`] takes a `Message`, so a message
//! that does not exist, or an argument of the wrong type, does not compile.

use crate::{FluentArgs, FluentValue};

/// Every string the product can show.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum Message {
    /// `action-new-conversation`
    ActionNewConversation,
    /// `action-send`
    ActionSend,
    /// `action-send-message`
    ActionSendMessage,
    /// `availability-available`
    AvailabilityAvailable,
    /// `availability-manifest-unreachable`
    AvailabilityManifestUnreachable,
    /// `availability-not-advertised`
    AvailabilityNotAdvertised,
    /// `availability-reported-unavailable`
    AvailabilityReportedUnavailable,
    /// `availability-unknown`
    AvailabilityUnknown,
    /// `chat-error-cancelled`
    ChatErrorCancelled,
    /// `chat-error-chat-id-missing`
    ChatErrorChatIdMissing,
    /// `chat-error-no-conversation`
    ChatErrorNoConversation,
    /// `chat-role-assistant`
    ChatRoleAssistant,
    /// `chat-role-you`
    ChatRoleYou,
    /// `chat-status-failed`
    ChatStatusFailed,
    /// `chat-status-sending`
    ChatStatusSending,
    /// `composer-error-authority-changed`
    ComposerErrorAuthorityChanged {
        current_epoch: u64,
    },
    /// `composer-error-outcome-missing`
    ComposerErrorOutcomeMissing,
    /// `composer-error-revision-conflict`
    ComposerErrorRevisionConflict {
        current: u64,
    },
    /// `composer-error-scope-mismatch`
    ComposerErrorScopeMismatch,
    /// `composer-error-scope-missing`
    ComposerErrorScopeMissing,
    /// `composer-error-snapshot-missing`
    ComposerErrorSnapshotMissing,
    /// `composer-placeholder`
    ComposerPlaceholder,
    /// `composer-status-connecting`
    ComposerStatusConnecting,
    /// `composer-status-failed`
    ComposerStatusFailed,
    /// `node-failure-cancelled`
    NodeFailureCancelled,
    /// `node-failure-conflict`
    NodeFailureConflict,
    /// `node-failure-internal`
    NodeFailureInternal,
    /// `node-failure-missing`
    NodeFailureMissing,
    /// `node-failure-overloaded`
    NodeFailureOverloaded,
    /// `node-failure-refused`
    NodeFailureRefused,
    /// `node-failure-rejected`
    NodeFailureRejected,
    /// `node-failure-timed-out`
    NodeFailureTimedOut,
    /// `node-failure-unreachable`
    NodeFailureUnreachable,
    /// `node-failure-unsupported`
    NodeFailureUnsupported,
    /// `rpc-error-already-exists`
    RpcErrorAlreadyExists,
    /// `rpc-error-cancelled`
    RpcErrorCancelled,
    /// `rpc-error-changed`
    RpcErrorChanged,
    /// `rpc-error-denied`
    RpcErrorDenied,
    /// `rpc-error-exhausted`
    RpcErrorExhausted,
    /// `rpc-error-internal`
    RpcErrorInternal,
    /// `rpc-error-not-found`
    RpcErrorNotFound,
    /// `rpc-error-rejected`
    RpcErrorRejected,
    /// `rpc-error-timed-out`
    RpcErrorTimedOut,
    /// `rpc-error-unavailable`
    RpcErrorUnavailable,
    /// `rpc-error-unsupported`
    RpcErrorUnsupported,
}

impl Message {
    /// The Fluent message id this variant names.
    #[must_use]
    pub const fn key(&self) -> &'static str {
        match self {
            Self::ActionNewConversation => "action-new-conversation",
            Self::ActionSend => "action-send",
            Self::ActionSendMessage => "action-send-message",
            Self::AvailabilityAvailable => "availability-available",
            Self::AvailabilityManifestUnreachable => "availability-manifest-unreachable",
            Self::AvailabilityNotAdvertised => "availability-not-advertised",
            Self::AvailabilityReportedUnavailable => "availability-reported-unavailable",
            Self::AvailabilityUnknown => "availability-unknown",
            Self::ChatErrorCancelled => "chat-error-cancelled",
            Self::ChatErrorChatIdMissing => "chat-error-chat-id-missing",
            Self::ChatErrorNoConversation => "chat-error-no-conversation",
            Self::ChatRoleAssistant => "chat-role-assistant",
            Self::ChatRoleYou => "chat-role-you",
            Self::ChatStatusFailed => "chat-status-failed",
            Self::ChatStatusSending => "chat-status-sending",
            Self::ComposerErrorAuthorityChanged { .. } => "composer-error-authority-changed",
            Self::ComposerErrorOutcomeMissing => "composer-error-outcome-missing",
            Self::ComposerErrorRevisionConflict { .. } => "composer-error-revision-conflict",
            Self::ComposerErrorScopeMismatch => "composer-error-scope-mismatch",
            Self::ComposerErrorScopeMissing => "composer-error-scope-missing",
            Self::ComposerErrorSnapshotMissing => "composer-error-snapshot-missing",
            Self::ComposerPlaceholder => "composer-placeholder",
            Self::ComposerStatusConnecting => "composer-status-connecting",
            Self::ComposerStatusFailed => "composer-status-failed",
            Self::NodeFailureCancelled => "node-failure-cancelled",
            Self::NodeFailureConflict => "node-failure-conflict",
            Self::NodeFailureInternal => "node-failure-internal",
            Self::NodeFailureMissing => "node-failure-missing",
            Self::NodeFailureOverloaded => "node-failure-overloaded",
            Self::NodeFailureRefused => "node-failure-refused",
            Self::NodeFailureRejected => "node-failure-rejected",
            Self::NodeFailureTimedOut => "node-failure-timed-out",
            Self::NodeFailureUnreachable => "node-failure-unreachable",
            Self::NodeFailureUnsupported => "node-failure-unsupported",
            Self::RpcErrorAlreadyExists => "rpc-error-already-exists",
            Self::RpcErrorCancelled => "rpc-error-cancelled",
            Self::RpcErrorChanged => "rpc-error-changed",
            Self::RpcErrorDenied => "rpc-error-denied",
            Self::RpcErrorExhausted => "rpc-error-exhausted",
            Self::RpcErrorInternal => "rpc-error-internal",
            Self::RpcErrorNotFound => "rpc-error-not-found",
            Self::RpcErrorRejected => "rpc-error-rejected",
            Self::RpcErrorTimedOut => "rpc-error-timed-out",
            Self::RpcErrorUnavailable => "rpc-error-unavailable",
            Self::RpcErrorUnsupported => "rpc-error-unsupported",
        }
    }

    /// The Fluent arguments this variant carries.
    #[must_use]
    pub fn args(&self) -> FluentArgs<'_> {
        let mut args = FluentArgs::new();
        match self {
            Self::ComposerErrorAuthorityChanged { current_epoch } => {
                args.set("currentEpoch", FluentValue::from(*current_epoch));
            }
            Self::ComposerErrorRevisionConflict { current } => {
                args.set("current", FluentValue::from(*current));
            }
            _ => {}
        }
        args
    }
}
