//! Emit the `Message` enum from `locales/en` into `OUT_DIR`.
//!
//! The enum is a function of the Fluent source, so it is a build artifact
//! rather than a file in the tree: cargo owns its freshness through
//! `rerun-if-changed`, and `cargo fmt --check` never has an opinion about
//! bytes a generator wrote. Every other output of the string source is a
//! native resource file that Xcode, Gradle and MSBuild read without cargo in
//! the loop, so `arut-dev generate` writes those instead.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

use arut_i18n_catalog::{Locale, Message, parse};

/// The locale the `Message` enum is generated from. Every other locale is
/// proved to define the same ids before any resource is written.
const SOURCE_LOCALE: &str = "en";

fn main() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let locales = manifest.join("locales");
    println!("cargo:rerun-if-changed={}", locales.display());
    println!("cargo:rerun-if-changed=build.rs");

    let locale = read(&locales.join(SOURCE_LOCALE));
    let out = PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets this"));
    fs::write(out.join("messages.rs"), messages(&locale)).expect("OUT_DIR is writable");
}

/// Parse one locale directory, panicking with every refusal at once: a message
/// the generatable subset rejects must not reach a build at all.
fn read(directory: &Path) -> Locale {
    let mut files: Vec<PathBuf> = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("{}: {error}", directory.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "ftl"))
        .collect();
    files.sort();
    let sources: Vec<(String, String)> = files
        .iter()
        .map(|file| {
            let name = file
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or_default()
                .to_owned();
            let text = fs::read_to_string(file).unwrap_or_else(|error| panic!("{name}: {error}"));
            (name, text)
        })
        .collect();
    let borrowed: Vec<(&str, &str)> = sources
        .iter()
        .map(|(name, text)| (name.as_str(), text.as_str()))
        .collect();
    parse(SOURCE_LOCALE, &borrowed).unwrap_or_else(|refusals| {
        let listed: Vec<String> = refusals.iter().map(ToString::to_string).collect();
        panic!("{}", listed.join("\n"));
    })
}

/// `composer-error-revision-conflict` -> `ComposerErrorRevisionConflict`.
fn pascal(id: &str) -> String {
    id.split('-')
        .map(|part| {
            let mut characters = part.chars();
            characters.next().map_or_else(String::new, |first| {
                first.to_uppercase().collect::<String>() + characters.as_str()
            })
        })
        .collect()
}

/// `currentEpoch` -> `current_epoch`, for Rust field names.
fn snake(name: &str) -> String {
    let mut out = String::new();
    for character in name.chars() {
        if character == '-' {
            out.push('_');
        } else if character.is_ascii_uppercase() {
            out.push('_');
            out.push(character.to_ascii_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}

/// One variant per message, its key, and its Fluent arguments.
fn messages(locale: &Locale) -> String {
    let messages = &locale.messages;
    let mut out = String::from(
        "// Generated by build.rs from product/i18n/locales. Do not edit.\n\
         //\n\
         // One variant per message in `locales/en/*.ftl`, carrying that message's\n\
         // Fluent arguments with the types the source declares. A key is never\n\
         // written by hand: `Localizer::format` takes a `Message`, so a message\n\
         // that does not exist, or an argument of the wrong type, does not compile.\n\
         \n\
         use crate::{FluentArgs, FluentValue};\n\
         \n\
         /// Every string the product can show.\n\
         #[derive(Clone, Debug, PartialEq, Eq)]\n\
         #[non_exhaustive]\n\
         pub enum Message {\n",
    );
    for (id, message) in messages {
        let arguments = message.arguments();
        let _ = writeln!(out, "    /// `{id}`");
        if arguments.is_empty() {
            let _ = writeln!(out, "    {},", pascal(id));
        } else {
            let _ = writeln!(out, "    {} {{", pascal(id));
            for argument in &arguments {
                let rust_type = if argument.numeric { "u64" } else { "String" };
                let _ = writeln!(out, "        {}: {rust_type},", snake(&argument.name));
            }
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\nimpl Message {\n    /// Every message id the string source defines, in order.\n    pub const KEYS: &'static [&'static str] = &[\n");
    for id in messages.keys() {
        let _ = writeln!(out, "        \"{id}\",");
    }
    out.push_str("    ];\n\n    /// The Fluent message id this variant names.\n    #[must_use]\n    pub const fn key(&self) -> &'static str {\n        match self {\n");
    for (id, message) in messages {
        let pattern = if message.arguments().is_empty() {
            format!("Self::{}", pascal(id))
        } else {
            format!("Self::{} {{ .. }}", pascal(id))
        };
        let _ = writeln!(out, "            {pattern} => \"{id}\",");
    }
    out.push_str(
        "        }\n    }\n\n    /// The Fluent arguments this variant carries.\n    #[must_use]\n    pub fn args(&self) -> FluentArgs<'_> {\n        let mut args = FluentArgs::new();\n",
    );
    out.push_str(&argument_arms(messages));
    out.push_str("        args\n    }\n}\n");
    out
}

/// Only the variants that carry something get an arm; a message with no
/// arguments is the whole rest of the enum.
fn argument_arms(messages: &BTreeMap<String, Message>) -> String {
    let carrying: Vec<(&String, &Message)> = messages
        .iter()
        .filter(|(_, message)| !message.arguments().is_empty())
        .collect();
    if carrying.is_empty() {
        return "        let _ = self;\n".to_owned();
    }
    let mut arms: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (id, message) in carrying {
        let arguments = message.arguments();
        let bindings = arguments
            .iter()
            .map(|argument| snake(&argument.name))
            .collect::<Vec<_>>()
            .join(", ");
        let mut body = String::new();
        for argument in &arguments {
            let value = if argument.numeric {
                format!("FluentValue::from(*{})", snake(&argument.name))
            } else {
                format!("FluentValue::from({}.as_str())", snake(&argument.name))
            };
            let _ = writeln!(
                body,
                "                args.set(\"{}\", {value});",
                argument.name
            );
        }
        arms.entry(body)
            .or_default()
            .push(format!("Self::{} {{ {bindings} }}", pascal(id)));
    }
    let mut out = String::from("        match self {\n");
    for (body, patterns) in arms {
        let _ = writeln!(out, "            {} => {{", patterns.join(" | "));
        out.push_str(&body);
        out.push_str("            }\n");
    }
    out.push_str("            _ => {}\n        }\n");
    out
}
