//! Generates native binding facades from the Rust FFI exports without mirroring data.
//! Swift and Kotlin alias types and forward factories; C# imports generated aliases
//! as source because aliases are not exported by assemblies. Observation stays in
//! each binding package. --check also rejects foreign FFI imports outside bindings.
use std::{collections::BTreeSet, error::Error, fs, path::Path, process::Command};
use syn::{FnArg, Item, Pat, ReturnType, Type, UseTree, Visibility};
type Result<T> = std::result::Result<T, Box<dyn Error>>;
const HEADER: &str = "// Generated by mise run bindings from Rust FFI exports. Do not edit.\n";

fn names(tree: &UseTree, into: &mut BTreeSet<String>) -> Result<()> {
    match tree {
        UseTree::Path(p) => names(&p.tree, into)?,
        UseTree::Group(g) => {
            for item in &g.items {
                names(item, into)?;
            }
        }
        UseTree::Name(n) => {
            into.insert(n.ident.to_string());
        }
        _ => return Err("FFI reexports must name types explicitly".into()),
    }
    Ok(())
}
fn camel(name: &str) -> String {
    let mut parts = name.split('_');
    let mut out = parts.next().unwrap_or_default().to_owned();
    for part in parts {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
        }
        out.push_str(chars.as_str());
    }
    out
}
fn native_type(ty: &Type) -> Result<String> {
    let Type::Path(path) = ty else {
        return Err("unsupported factory type".into());
    };
    let segment = path.path.segments.last().ok_or("empty type")?;
    if segment.ident == "Arc" {
        let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
            return Err("Arc requires a callback".into());
        };
        let Some(syn::GenericArgument::Type(Type::TraitObject(object))) = args.args.first() else {
            return Err("only callback Arc types are supported".into());
        };
        let Some(syn::TypeParamBound::Trait(bound)) = object.bounds.first() else {
            return Err("missing callback trait".into());
        };
        return Ok(bound
            .path
            .segments
            .last()
            .ok_or("empty callback")?
            .ident
            .to_string());
    }
    Ok(segment.ident.to_string())
}
fn factory(function: &syn::ItemFn, swift: &mut String, kotlin: &mut String) -> Result<()> {
    let name = camel(&function.sig.ident.to_string());
    let ReturnType::Type(_, result) = &function.sig.output else {
        return Err("factory needs a return type".into());
    };
    let result = native_type(result)?;
    let mut parameters = Vec::new();
    let mut labels = Vec::new();
    let mut values = Vec::new();
    for arg in &function.sig.inputs {
        let FnArg::Typed(arg) = arg else {
            return Err("factory cannot take self".into());
        };
        let Pat::Ident(pat) = &*arg.pat else {
            return Err("factory parameter must be named".into());
        };
        let name = camel(&pat.ident.to_string());
        parameters.push(format!("{name}: {}", native_type(&arg.ty)?));
        labels.push(format!("{name}: {name}"));
        values.push(name);
    }
    let params = parameters.join(", ");
    swift.push_str(&format!(
        "\npublic func {name}({params}) -> {result} {{\n    ArutFfi.{name}({})\n}}\n",
        labels.join(", ")
    ));
    kotlin.push_str(&format!(
        "\nfun {name}({params}): {result} =\n    dev.arut.ffi.{name}({})\n",
        values.join(", ")
    ));
    Ok(())
}
fn streams(ffi: &syn::File, kotlin_imports: &mut String, kotlin: &mut String) -> Result<()> {
    for item in &ffi.items {
        let Item::Impl(item) = item else { continue };
        if !item.attrs.iter().any(|a| a.path().is_ident("export")) {
            continue;
        }
        let Type::Path(self_ty) = &*item.self_ty else {
            continue;
        };
        let handle = self_ty
            .path
            .segments
            .last()
            .ok_or("empty impl type")?
            .ident
            .to_string();
        for member in &item.items {
            let syn::ImplItem::Fn(method) = member else {
                continue;
            };
            if !method.attrs.iter().any(|a| a.path().is_ident("ffi_stream")) {
                continue;
            }
            let name = camel(&method.sig.ident.to_string());
            let mut cancellable = name.clone();
            if let Some(first) = cancellable.get_mut(0..1) {
                first.make_ascii_uppercase();
            }
            cancellable.push_str("Cancellable");
            kotlin_imports.push_str(&format!("import dev.arut.ffi.{name} as ffi_{name}\n"));
            kotlin.push_str(&format!(
                "\ntypealias {cancellable} = dev.arut.ffi.{cancellable}\nfun {handle}.{name}(callback: (ULong) -> Unit): {cancellable} =\n    this.ffi_{name}(callback)\n"
            ));
        }
    }
    Ok(())
}
fn variants(dir: &Path, exports: &BTreeSet<String>, into: &mut String) -> Result<()> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            variants(&path, exports, into)?;
        } else if path.extension().is_some_and(|e| e == "rs") {
            for item in syn::parse_file(&fs::read_to_string(path)?)?.items {
                if let Item::Enum(item) = item {
                    let name = item.ident.to_string();
                    if exports.contains(&name) && item.variants.iter().any(|v| !v.fields.is_empty())
                    {
                        for variant in item.variants {
                            let variant = variant.ident;
                            into.push_str(&format!(
                                "typealias {name}{variant} = dev.arut.ffi.{name}.{variant}\n"
                            ));
                        }
                    }
                }
            }
        }
    }
    Ok(())
}
fn generated(root: &Path) -> Result<[(&'static str, String); 3]> {
    let ffi = syn::parse_file(&fs::read_to_string(root.join("bindings/ffi/src/lib.rs"))?)?;
    let mut exports = BTreeSet::new();
    let mut functions = Vec::new();
    for item in ffi.items.clone() {
        match item {
            Item::Use(item) if matches!(item.vis, Visibility::Public(_)) => {
                names(&item.tree, &mut exports)?;
            }
            Item::Struct(item) if matches!(item.vis, Visibility::Public(_)) => {
                exports.insert(item.ident.to_string());
            }
            Item::Trait(item) if matches!(item.vis, Visibility::Public(_)) => {
                exports.insert(item.ident.to_string());
            }
            Item::Fn(item) if item.attrs.iter().any(|a| a.path().is_ident("export")) => {
                functions.push(item);
            }
            _ => {}
        }
    }
    let mut swift = format!("{HEADER}import ArutFfi\n\n");
    let mut kotlin_imports = String::new();
    let mut kotlin_streams = String::new();
    streams(&ffi, &mut kotlin_imports, &mut kotlin_streams)?;
    let mut kotlin = format!("{HEADER}package dev.arut.bindings\n\n{kotlin_imports}\n");
    let mut csharp = format!(
        "{HEADER}global using Arut_ffi = global::Arut.Ffi.Arut_ffi;\nglobal using static global::Arut.Ffi.Arut_ffi;\n"
    );
    for name in &exports {
        swift.push_str(&format!("public typealias {name} = ArutFfi.{name}\n"));
        kotlin.push_str(&format!("typealias {name} = dev.arut.ffi.{name}\n"));
        csharp.push_str(&format!("global using {name} = global::Arut.Ffi.{name};\n"));
    }
    // Kotlin aliases do not make nested sealed variants available through the alias.
    let mut nested = String::new();
    variants(&root.join("features"), &exports, &mut nested)?;
    variants(&root.join("product"), &exports, &mut nested)?;
    let mut nested: Vec<_> = nested.lines().collect();
    nested.sort_unstable();
    for line in nested {
        kotlin.push_str(line);
        kotlin.push('\n');
    }
    for function in functions {
        factory(&function, &mut swift, &mut kotlin)?;
    }
    kotlin.push_str(&kotlin_streams);
    Ok([
        ("bindings/swift/Sources/ArutBindings/Exports.swift", swift),
        (
            "bindings/kotlin/src/main/kotlin/dev/arut/bindings/Exports.kt",
            kotlin,
        ),
        ("bindings/dotnet/Exports.cs", csharp),
    ])
}
/// Relative source paths must stay within their surface or runtime package.
fn crosses_package(file: &str, specifier: &str) -> bool {
    if !specifier.starts_with("./") && !specifier.starts_with("../") {
        return false;
    }
    let mut path: Vec<_> = file.split('/').collect();
    path.pop();
    let owner: Vec<_> = path.iter().take(2).copied().collect();
    if !matches!(owner.first(), Some(&"surfaces" | &"runtimes")) {
        return false;
    }
    for component in specifier.split('/') {
        match component {
            "." => {}
            ".." => {
                path.pop();
            }
            component => path.push(component),
        }
    }
    !path.starts_with(&owner)
}

fn imports(root: &Path) -> Result<Vec<String>> {
    let output = Command::new("git")
        .args([
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "-z",
        ])
        .current_dir(root)
        .output()?;
    if !output.status.success() {
        return Err("git ls-files failed".into());
    }
    let mut violations = Vec::new();
    for file in String::from_utf8(output.stdout)?
        .split('\0')
        .filter(|f| !f.is_empty())
    {
        if file.starts_with("bindings/") {
            continue;
        }
        if !matches!(
            Path::new(file).extension().and_then(|e| e.to_str()),
            Some("swift" | "kt" | "cs" | "ts" | "tsx")
        ) {
            continue;
        }
        let path = root.join(file);
        if !path.exists() {
            continue;
        }
        for (line, text) in fs::read_to_string(path)?.lines().enumerate() {
            for specifier in text.split(['\'', '"', '`']).skip(1).step_by(2) {
                if matches!(
                    Path::new(file).extension().and_then(|e| e.to_str()),
                    Some("ts" | "tsx")
                ) && crosses_package(file, specifier)
                {
                    violations.push(format!(
                        "{file}:{} -> {specifier}: import through a workspace package",
                        line + 1
                    ));
                }
            }
            if ["ArutFfi", "dev.arut.ffi", "Arut.Ffi", "@arut/ffi"]
                .iter()
                .any(|package| text.contains(package))
            {
                violations.push(format!(
                    "{file}:{} -> generated FFI: import through bindings",
                    line + 1
                ));
            }
        }
    }
    Ok(violations)
}
pub(crate) fn run(check: bool) -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .ok_or("missing repository")?;
    let mut violations = imports(root)?;
    for (file, contents) in generated(root)? {
        let path = root.join(file);
        if fs::read_to_string(&path).is_ok_and(|current| current == contents) {
            continue;
        }
        if check {
            violations.push(format!(
                "{file}: stale binding facade; run mise run bindings"
            ));
        } else {
            fs::write(path, contents)?;
        }
    }
    for violation in &violations {
        eprintln!("{violation}");
    }
    if !violations.is_empty() {
        std::process::exit(1);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn relative_paths_cannot_escape_surface_or_runtime_packages() {
        for (file, specifier) in [
            ("surfaces/web/src/main.tsx", "../../../runtimes/browser/ids"),
            ("surfaces/chromium/src/main.tsx", "../../web/src/main"),
            ("runtimes/browser/ids.ts", "../../surfaces/web/src/main"),
        ] {
            assert!(crosses_package(file, specifier));
        }
        for specifier in ["./view", "../style.css", "@arut/runtime-browser"] {
            assert!(!crosses_package("surfaces/web/src/main.tsx", specifier));
        }
    }
}
