//! Turn `bindings/ffi/handles.toml` into the `#[export]` blocks BoltFFI scans.
//!
//! Every scope handle answers the same four questions -- what does it project,
//! what went wrong, what scopes hang under it, when did it change -- and the
//! answer is the same shape every time. ADR 0021's amendment says the way to
//! stop writing that shape by hand is a generator that writes source, because
//! BoltFFI's scanner expands no macros: a handle behind a macro disappears from
//! the bindings without an error. So this emits Rust, the Rust is checked in,
//! and `arut-dev check` regenerates it and diffs, exactly as the localization
//! resources work.
//!
//! What is not here is what a person does. Intents keep their own
//! `#[export] impl` block in `bindings/ffi/src/intents.rs`: Rust allows several
//! inherent impls on one type and the scanner reads each of them, so the
//! repeated half is generated and the feature-specific half stays reviewable.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use serde::Deserialize;

use crate::output::{Outcome, Run, write};

/// Where the declaration and its output live, relative to the repository root.
pub(crate) const DECLARATION: &str = "bindings/ffi/handles.toml";
pub(crate) const OUTPUT: &str = "bindings/ffi/src/generated/handles.rs";

const BANNER: &str =
    "Generated by `mise run generate` from bindings/ffi/handles.toml. Do not edit.";

#[derive(Deserialize)]
pub(crate) struct Declaration {
    /// The `use` lines the emitted module needs, verbatim. Type names reach
    /// BoltFFI's scanner the way the rest of the crate writes them.
    #[serde(default)]
    imports: Vec<String>,
    #[serde(default, rename = "handle")]
    handles: Vec<Handle>,
}

#[derive(Deserialize)]
struct Handle {
    name: String,
    holds: String,
    #[serde(default)]
    shared: bool,
    #[serde(default)]
    state: Option<String>,
    #[serde(default)]
    state_from: Option<String>,
    #[serde(default)]
    error: Option<String>,
    #[serde(default)]
    changes: Option<String>,
    #[serde(default)]
    changes_from: Option<String>,
    #[serde(default)]
    reads: BTreeMap<String, Read>,
    #[serde(default)]
    children: BTreeMap<String, Child>,
    #[serde(default)]
    rows: Option<Rows>,
}

/// One further read off the same value, beyond the projection itself.
#[derive(Deserialize)]
struct Read {
    returns: String,
    #[serde(default)]
    from: Option<String>,
}

/// A scope that hangs under this one.
#[derive(Deserialize)]
struct Child {
    handle: String,
    /// The method that produces the child's value.
    #[serde(default)]
    from: Option<String>,
    /// The child holds the same shared value this handle does.
    #[serde(default)]
    share: bool,
}

/// Keyed rows read by cursor, the transcript shape.
#[derive(Deserialize)]
struct Rows {
    after: String,
    row: String,
}

/// Read the declaration beside the crate it describes.
///
/// # Errors
///
/// Fails when the file is missing or is not the shape above.
pub(crate) fn declaration(root: &Path) -> Result<Declaration, String> {
    let path = root.join(DECLARATION);
    let source = std::fs::read_to_string(&path)
        .map_err(|error| format!("could not read {}: {error}", path.display()))?;
    toml::from_str(&source).map_err(|error| format!("{}: {error}", path.display()))
}

/// Write the emitted module, or report that the checked-in copy differs.
///
/// # Errors
///
/// Fails when the declaration cannot be read or the output cannot be written.
pub(crate) fn run(root: &Path, run: Run) -> Result<Outcome, String> {
    let declaration = declaration(root)?;
    let mut written = Vec::new();
    let mut stale = Vec::new();
    write(
        root.join(OUTPUT),
        &emit(&declaration),
        &mut written,
        &mut stale,
        run,
    )?;
    Ok(Outcome { written, stale })
}

/// The whole generated module, as one deterministic string.
#[must_use]
pub(crate) fn emit(declaration: &Declaration) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "//! {BANNER}");
    out.push_str(
        "//!\n\
         //! One `#[export] impl` per scope handle: its projection, its typed error as\n\
         //! a Fluent id and arguments, its child scopes, its keyed rows and its\n\
         //! revision stream. Intents live in `crate::intents`, in a second\n\
         //! `#[export] impl` block on the same type.\n\n",
    );
    for import in &declaration.imports {
        let _ = writeln!(out, "use {import};");
    }
    for handle in &declaration.handles {
        out.push('\n');
        out.push_str(&structure(handle));
        out.push('\n');
        out.push_str(&block(handle));
    }
    out
}

fn structure(handle: &Handle) -> String {
    let Handle { name, holds, .. } = handle;
    let held = if handle.shared {
        format!("Arc<{holds}>")
    } else {
        holds.clone()
    };
    format!(
        "/// The `{holds}` scope, as the bindings export it.\n\
         pub struct {name} {{\n\
         \x20   pub(crate) inner: {held},\n\
         }}\n"
    )
}

fn block(handle: &Handle) -> String {
    let mut out = format!("#[export]\nimpl {} {{\n", handle.name);
    let mut first = true;
    let mut method = |body: &str, out: &mut String| {
        if !first {
            out.push('\n');
        }
        first = false;
        out.push_str(body);
    };
    if let Some(state) = &handle.state {
        let from = handle.state_from.as_deref().unwrap_or("state");
        method(
            &format!(
                "    /// What this scope publishes right now.\n\
                 \x20   pub fn state(&self) -> {state} {{\n\
                 \x20       self.inner.{from}()\n\
                 \x20   }}\n"
            ),
            &mut out,
        );
    }
    for (name, read) in &handle.reads {
        let from = read.from.as_deref().unwrap_or(name);
        let returns = &read.returns;
        method(
            &format!(
                "    /// `{from}`, read off the same scope as `state`.\n\
                 \x20   pub fn {name}(&self) -> {returns} {{\n\
                 \x20       self.inner.{from}()\n\
                 \x20   }}\n"
            ),
            &mut out,
        );
    }
    if let Some(error) = &handle.error {
        method(&errors(error), &mut out);
    }
    for (name, child) in &handle.children {
        let Child {
            handle: child_handle,
            ..
        } = child;
        let inner = if child.share {
            "self.inner.clone()".to_owned()
        } else {
            format!("self.inner.{}()", child.from.as_deref().unwrap_or(name))
        };
        method(
            &format!(
                "    /// The `{child_handle}` scope under this one.\n\
                 \x20   pub fn {name}(&self) -> {child_handle} {{\n\
                 \x20       {child_handle} {{\n\
                 \x20           inner: {inner},\n\
                 \x20       }}\n\
                 \x20   }}\n"
            ),
            &mut out,
        );
    }
    if let Some(rows) = &handle.rows {
        let Rows { after, row } = rows;
        method(
            &format!(
                "    /// The rows after `after_id`, which never change once keyed, so a\n\
                 \x20   /// surface appends what it does not have.\n\
                 \x20   pub fn {after}(&self, after_id: u64) -> Vec<{row}> {{\n\
                 \x20       self.inner.{after}(after_id)\n\
                 \x20   }}\n"
            ),
            &mut out,
        );
    }
    if let Some(changes) = &handle.changes {
        let from = handle.changes_from.as_deref().unwrap_or("changes");
        method(
            &format!(
                "    /// One revision per change to what this scope publishes. Each\n\
                 \x20   /// ecosystem receives its own stream idiom (ADR 0021).\n\
                 \x20   #[ffi_stream(item = u64, mode = \"async\")]\n\
                 \x20   pub fn {changes}(&self) -> Arc<EventSubscription<u64>> {{\n\
                 \x20       subscription(self.inner.{from}())\n\
                 \x20   }}\n"
            ),
            &mut out,
        );
    }
    out.push_str("}\n");
    out
}

/// The two error reads, which are the same on every handle: a Fluent message id
/// and the arguments that message interpolates, never a sentence (ADR 0016,
/// ADR 0022).
fn errors(error: &str) -> String {
    format!(
        "    /// The Fluent message id of the current `{error}`, if there is one.\n\
         \x20   pub fn error_key(&self) -> Option<String> {{\n\
         \x20       self.inner\n\
         \x20           .state()\n\
         \x20           .error\n\
         \x20           .map(|error| error.message_key().to_owned())\n\
         \x20   }}\n\
         \n\
         \x20   /// The arguments that message interpolates, each under the name it is\n\
         \x20   /// selected by, in the order every generated catalog reads them.\n\
         \x20   pub fn error_args(&self) -> Vec<ErrorArg> {{\n\
         \x20       self.inner\n\
         \x20           .state()\n\
         \x20           .error\n\
         \x20           .map(|error| {{\n\
         \x20               error\n\
         \x20                   .message_args()\n\
         \x20                   .into_iter()\n\
         \x20                   .map(ErrorArg::from)\n\
         \x20                   .collect()\n\
         \x20           }})\n\
         \x20           .unwrap_or_default()\n\
         \x20   }}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::{Declaration, emit};

    fn chat() -> Declaration {
        toml::from_str(
            r#"
imports = ["crate::ErrorArg"]

[[handle]]
name = "ChatHandle"
holds = "ChatClient"
state = "ChatState"
error = "ChatError"
changes = "chat_changes"
rows = { after = "messages_after", row = "ChatMessage" }

[handle.children]
composer = { handle = "ComposerHandle", from = "composer" }
"#,
        )
        .expect("the declaration parses")
    }

    #[test]
    fn one_declaration_emits_the_whole_scope_handle() {
        let expected = include_str!("../tests/handles/chat.rs");
        assert_eq!(emit(&chat()), expected);
    }

    #[test]
    fn emission_is_a_function_of_the_declaration_alone() {
        assert_eq!(emit(&chat()), emit(&chat()));
    }
}
