// Generated by mise run bindings from Rust FFI exports. Do not edit.
package dev.arut.bindings

typealias AvailabilityHandle = dev.arut.ffi.AvailabilityHandle
typealias ChatError = dev.arut.ffi.ChatError
typealias ChatHandle = dev.arut.ffi.ChatHandle
typealias ChatMessage = dev.arut.ffi.ChatMessage
typealias ChatRole = dev.arut.ffi.ChatRole
typealias ChatState = dev.arut.ffi.ChatState
typealias ChatStatus = dev.arut.ffi.ChatStatus
typealias ChatSummary = dev.arut.ffi.ChatSummary
typealias ComposerError = dev.arut.ffi.ComposerError
typealias ComposerHandle = dev.arut.ffi.ComposerHandle
typealias ComposerState = dev.arut.ffi.ComposerState
typealias ComposerStatus = dev.arut.ffi.ComposerStatus
typealias ConversationsHandle = dev.arut.ffi.ConversationsHandle
typealias FeatureAvailability = dev.arut.ffi.FeatureAvailability
typealias HostIds = dev.arut.ffi.HostIds
typealias NodeFailure = dev.arut.ffi.NodeFailure
typealias ProductSessionHandle = dev.arut.ffi.ProductSessionHandle
typealias SessionAvailability = dev.arut.ffi.SessionAvailability
typealias ChatErrorCancelled = dev.arut.ffi.ChatError.Cancelled
typealias ChatErrorChatIdMissing = dev.arut.ffi.ChatError.ChatIdMissing
typealias ChatErrorDraft = dev.arut.ffi.ChatError.Draft
typealias ChatErrorNoConversation = dev.arut.ffi.ChatError.NoConversation
typealias ChatErrorNode = dev.arut.ffi.ChatError.Node
typealias ComposerErrorAuthorityChanged = dev.arut.ffi.ComposerError.AuthorityChanged
typealias ComposerErrorNode = dev.arut.ffi.ComposerError.Node
typealias ComposerErrorOutcomeMissing = dev.arut.ffi.ComposerError.OutcomeMissing
typealias ComposerErrorRevisionConflict = dev.arut.ffi.ComposerError.RevisionConflict
typealias ComposerErrorScopeMismatch = dev.arut.ffi.ComposerError.ScopeMismatch
typealias ComposerErrorScopeMissing = dev.arut.ffi.ComposerError.ScopeMissing
typealias ComposerErrorSnapshotMissing = dev.arut.ffi.ComposerError.SnapshotMissing

fun createProductSession(pendingScopeId: String): ProductSessionHandle =
    dev.arut.ffi.createProductSession(pendingScopeId)

fun createBrowserSession(pendingScopeId: String, ids: HostIds): ProductSessionHandle =
    dev.arut.ffi.createBrowserSession(pendingScopeId, ids)
