//! Turn `product/i18n/locales/*.ftl` into each platform's native resources.
//!
//! One source, two kinds of output (ADR 0022). The resources each platform's
//! localization API reads -- Apple's string catalog, Android's `strings.xml`
//! per locale, a Windows `.resw` per locale -- and the files that name those
//! resources without a key being typed by hand: Swift and C# constants, the
//! Kotlin map from a Fluent id to its Android resource, and a TypeScript key
//! union beside the Fluent text the browser runtime formats from.
//!
//! The Rust `Message` enum is not here. It is the one output cargo genuinely
//! owns, so `product/i18n/build.rs` writes it to `OUT_DIR`; this binary writes
//! only the files Xcode, Gradle, MSBuild and Vite read without cargo in the
//! loop.
//!
//! The `.ftl` files reach this binary through `arut_i18n`'s own embedded
//! copies, so the generator and the Rust runtime can never read different
//! sources.
//!
//! Run it with `mise run generate`. It is deterministic and idempotent, and
//! `mise run check` regenerates into memory and fails naming every file that
//! would change, which is how "the `.ftl` is the source" is enforced both
//! before a commit and in CI.

mod accessors;
mod targets;

use std::path::Path;

use arut_i18n::{DEFAULT_LOCALE, available_locales, locale_resources};
use arut_i18n_catalog::{Locale, parse, require_identical_key_sets};

use crate::output::{Outcome, Run, write};

const BANNER: &str = "Generated by `mise run generate` from product/i18n/locales. Do not edit.";

/// Android and Windows resource keys, shared by resources and typed accessors.
fn resource_name(id: &str) -> String {
    id.replace('-', "_")
}

/// Where each output lands, relative to the repository root.
const XCSTRINGS: &str = "surfaces/apple/shared/Sources/ArutSurface/Resources/Localizable.xcstrings";
const ANDROID_RES: &str = "bindings/kotlin/src/main/res";
const WINDOWS_STRINGS: &str = "surfaces/windows/Strings";
const SWIFT_L10N: &str = "surfaces/apple/shared/Sources/ArutSurface/Generated/L10n.swift";
const KOTLIN_MESSAGES: &str =
    "bindings/kotlin/src/main/kotlin/dev/arut/bindings/generated/Messages.kt";
const CSHARP_L10N: &str = "surfaces/windows/Generated/L10n.cs";
const TYPESCRIPT_L10N: &str = "bindings/typescript/src/generated/l10n.ts";
const TYPESCRIPT_CATALOG: &str = "bindings/typescript/src/generated/catalog.ts";

pub(crate) fn run(root: &Path, run: Run) -> Result<Outcome, String> {
    let locales = catalog()?;
    let mut written = Vec::new();
    let mut stale = Vec::new();
    for (path, contents) in [
        (XCSTRINGS, targets::xcstrings(DEFAULT_LOCALE, &locales)),
        (SWIFT_L10N, accessors::swift(DEFAULT_LOCALE, &locales)),
        (KOTLIN_MESSAGES, accessors::kotlin(DEFAULT_LOCALE, &locales)),
        (CSHARP_L10N, accessors::csharp(DEFAULT_LOCALE, &locales)),
        (
            TYPESCRIPT_L10N,
            accessors::typescript(DEFAULT_LOCALE, &locales),
        ),
        (TYPESCRIPT_CATALOG, accessors::typescript_catalog()),
    ] {
        write(root.join(path), &contents, &mut written, &mut stale, run)?;
    }
    for locale in &locales {
        let values = if locale.tag == DEFAULT_LOCALE {
            "values".to_owned()
        } else {
            format!("values-{}", locale.tag)
        };
        write(
            root.join(ANDROID_RES).join(values).join("strings.xml"),
            &targets::strings_xml(locale),
            &mut written,
            &mut stale,
            run,
        )?;
        write(
            root.join(WINDOWS_STRINGS)
                .join(&locale.tag)
                .join("Resources.resw"),
            &targets::resw(locale),
            &mut written,
            &mut stale,
            run,
        )?;
    }
    written.sort();
    stale.sort();
    Ok(Outcome { written, stale })
}

/// Every `x:Uid` the generated `.resw` defines entries for.
///
/// # Errors
///
/// Fails for the same reasons generation does, since it parses the same
/// source.
pub(crate) fn uid_names() -> Result<std::collections::BTreeSet<String>, String> {
    let locales = catalog()?;
    let default = locales
        .iter()
        .find(|locale| locale.tag == DEFAULT_LOCALE)
        .ok_or_else(|| format!("{DEFAULT_LOCALE} is not shipped"))?;
    Ok(targets::uid_names(default))
}

/// Every shipped locale, parsed into the generatable subset and proved to
/// define the same ids.
fn catalog() -> Result<Vec<Locale>, String> {
    let mut locales = Vec::new();
    let mut refusals = Vec::new();
    for tag in available_locales() {
        match parse(tag, locale_resources(tag)) {
            Ok(locale) => locales.push(locale),
            Err(mut refused) => refusals.append(&mut refused),
        }
    }
    if !refusals.is_empty() {
        let listed = refusals
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n");
        return Err(format!(
            "{} message(s) cannot be generated:\n{listed}",
            refusals.len()
        ));
    }
    // A typed accessor compiles against one key set, so every locale has to
    // define the same ids before a single file is written.
    require_identical_key_sets(&locales)?;
    Ok(locales)
}

#[cfg(test)]
mod tests {
    use super::run;
    use crate::output::{Run, repository_root};

    #[test]
    fn the_shipped_locales_all_generate() {
        let root = tempdir();
        let written = run(&root, Run::Write)
            .expect("the shipped .ftl files are generatable")
            .written;
        for expected in [
            "Localizable.xcstrings",
            "values/strings.xml",
            "en/Resources.resw",
            "L10n.swift",
            "Messages.kt",
            "L10n.cs",
            "l10n.ts",
            "catalog.ts",
        ] {
            assert!(
                written.iter().any(|path| path.ends_with(expected)),
                "{expected} was not written"
            );
        }
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn a_second_run_produces_the_same_bytes() {
        let root = tempdir();
        let first = run(&root, Run::Write).expect("first run").written;
        let before: Vec<String> = first
            .iter()
            .map(|path| std::fs::read_to_string(path).expect("written"))
            .collect();
        let second = run(&root, Run::Write).expect("second run").written;
        assert_eq!(first, second);
        let after: Vec<String> = second
            .iter()
            .map(|path| std::fs::read_to_string(path).expect("written"))
            .collect();
        assert_eq!(before, after);
        // And a check over what was just written finds nothing to do.
        let outcome = run(&root, Run::Check).expect("check run");
        assert!(outcome.stale.is_empty(), "{:?}", outcome.stale);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn a_check_over_an_empty_tree_names_every_file_it_would_write() {
        let root = tempdir();
        let outcome = run(&root, Run::Check).expect("check run");
        assert!(outcome.written.is_empty());
        assert!(outcome.stale.iter().any(|path| path.ends_with("l10n.ts")));
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn the_repository_root_is_the_one_holding_the_source() {
        assert!(repository_root().join("product/i18n/locales").is_dir());
    }

    fn tempdir() -> std::path::PathBuf {
        let root = std::env::temp_dir().join(format!(
            "arut-dev-i18n-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).expect("a temporary directory");
        root
    }
}
