//! One emitter per platform resource format.
//!
//! Each takes the same parsed catalog and writes the file that platform's own
//! localization API reads, so no surface learns about Fluent (ADR 0022). The
//! output is sorted and byte-stable: `mise run check` regenerates and fails on
//! any diff, which only works if the same input always writes the same bytes.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::i18n::catalog::{Argument, Locale, Message, Part, Pattern};

/// The header every generated file carries, so nobody edits the wrong copy.
const BANNER: &str = "Generated by `mise run i18n` from product/i18n/locales. Do not edit.";

/// Apple, Android and Windows resource names are identifiers; Fluent ids are
/// kebab-case. Only Apple's string catalog takes the id verbatim.
fn resource_name(id: &str) -> String {
    id.replace('-', "_")
}

/// `%1$@` / `%1$lld`, positional so a translation may reorder them.
fn apple_placeholder(index: usize, argument: &Argument) -> String {
    format!(
        "%{}${}",
        index + 1,
        if argument.numeric() { "lld" } else { "@" }
    )
}

/// `%1$s` / `%1$d`, the only form `Resources.getString(id, ...)` accepts once
/// a string has more than one argument.
fn android_placeholder(index: usize, argument: &Argument) -> String {
    format!(
        "%{}${}",
        index + 1,
        if argument.numeric() { "d" } else { "s" }
    )
}

/// `{0}`, which is what `string.Format` over a `ResourceLoader` string expects.
fn windows_placeholder(index: usize, _argument: &Argument) -> String {
    format!("{{{index}}}")
}

/// Render one pattern with a target's placeholder syntax and text escaping.
fn render(
    pattern: &Pattern,
    order: &[Argument],
    placeholder: fn(usize, &Argument) -> String,
    escape: fn(&str) -> String,
) -> String {
    let mut out = String::new();
    for part in &pattern.parts {
        match part {
            Part::Text(text) => out.push_str(&escape(text)),
            Part::Argument(argument) => {
                let index = order
                    .iter()
                    .position(|candidate| candidate.name == argument.name)
                    .expect("every argument is in the shared order");
                out.push_str(&placeholder(index, argument));
            }
        }
    }
    out
}

/// Apple takes `%` literally except in a format specifier.
fn apple_text(text: &str) -> String {
    text.replace('%', "%%")
}

/// Android's XML resource parser eats apostrophes and quotes unless they are
/// escaped, and reads `@` or `?` in first position as a resource reference.
fn android_text(text: &str) -> String {
    let escaped = text
        .replace('\\', "\\\\")
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('%', "%%")
        .replace('\'', "\\'")
        .replace('"', "\\\"")
        .replace('\n', "\\n");
    if escaped.starts_with('@') || escaped.starts_with('?') {
        format!("\\{escaped}")
    } else {
        escaped
    }
}

/// `string.Format` reads braces as placeholders, so literal ones are doubled.
fn windows_text(text: &str) -> String {
    xml_text(&text.replace('{', "{{").replace('}', "}}"))
}

fn xml_text(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Apple's string catalog, the format Xcode reads directly.
///
/// Written through `serde_json` over sorted maps, so the bytes are a function
/// of the input alone.
#[must_use]
pub(crate) fn xcstrings(source_locale: &str, locales: &[Locale]) -> String {
    let ids: Vec<&String> = {
        let mut ids: Vec<&String> = locales
            .iter()
            .flat_map(|locale| locale.messages.keys())
            .collect();
        ids.sort_unstable();
        ids.dedup();
        ids
    };
    let mut strings = serde_json::Map::new();
    for id in ids {
        let mut localizations = serde_json::Map::new();
        for locale in locales {
            let Some(message) = locale.messages.get(id) else {
                continue;
            };
            let order = message.arguments();
            let body = match message {
                Message::Simple(pattern) => serde_json::json!({
                    "stringUnit": unit(&render(pattern, &order, apple_placeholder, apple_text)),
                }),
                Message::Plural { variants, .. } => {
                    let mut plural = serde_json::Map::new();
                    for (category, pattern) in variants {
                        plural.insert(
                            category.name().to_owned(),
                            serde_json::json!({
                                "stringUnit": unit(&render(
                                    pattern, &order, apple_placeholder, apple_text,
                                )),
                            }),
                        );
                    }
                    serde_json::json!({ "variations": { "plural": plural } })
                }
            };
            localizations.insert(locale.tag.clone(), body);
        }
        strings.insert(
            (*id).clone(),
            serde_json::json!({
                "extractionState": "manual",
                "localizations": localizations,
            }),
        );
    }
    let catalog = serde_json::json!({
        "sourceLanguage": source_locale,
        "strings": strings,
        "version": "1.0",
    });
    let mut out = serde_json::to_string_pretty(&catalog).expect("a catalog serializes");
    out.push('\n');
    out
}

fn unit(value: &str) -> serde_json::Value {
    serde_json::json!({ "state": "translated", "value": value })
}

/// One Android `values/strings.xml` (or `values-<lang>/strings.xml`).
#[must_use]
pub(crate) fn strings_xml(locale: &Locale) -> String {
    let mut out = String::from("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
    let _ = writeln!(out, "<!-- {BANNER} -->");
    out.push_str("<resources>\n");
    for (id, message) in &locale.messages {
        let name = resource_name(id);
        let order = message.arguments();
        match message {
            Message::Simple(pattern) => {
                let value = render(pattern, &order, android_placeholder, android_text);
                let _ = writeln!(out, "    <string name=\"{name}\">{value}</string>");
            }
            Message::Plural { variants, .. } => {
                let _ = writeln!(out, "    <plurals name=\"{name}\">");
                for (category, pattern) in variants {
                    let value = render(pattern, &order, android_placeholder, android_text);
                    let _ = writeln!(
                        out,
                        "        <item quantity=\"{}\">{value}</item>",
                        category.name()
                    );
                }
                out.push_str("    </plurals>\n");
            }
        }
    }
    out.push_str("</resources>\n");
    out
}

/// One Windows `.resw`.
///
/// `.resw` is a flat name-to-string map with no plural mechanism, so a plural
/// message becomes one entry per category, named `<key>_<category>`; that is
/// the shape WinUI's own plural resources take and what `ResourceLoader`
/// lookups by suffix expect.
#[must_use]
pub(crate) fn resw(locale: &Locale) -> String {
    let mut entries: BTreeMap<String, (String, Option<&'static str>)> = BTreeMap::new();
    for (id, message) in &locale.messages {
        let name = resource_name(id);
        let order = message.arguments();
        match message {
            Message::Simple(pattern) => {
                entries.insert(
                    name,
                    (
                        render(pattern, &order, windows_placeholder, windows_text),
                        None,
                    ),
                );
            }
            Message::Plural { variants, .. } => {
                for (category, pattern) in variants {
                    entries.insert(
                        format!("{name}_{}", category.name()),
                        (
                            render(pattern, &order, windows_placeholder, windows_text),
                            Some(category.name()),
                        ),
                    );
                }
            }
        }
    }
    let mut out = String::from("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
    let _ = writeln!(out, "<!-- {BANNER} -->");
    out.push_str(RESW_HEADER);
    for (name, (value, comment)) in entries {
        let _ = writeln!(out, "  <data name=\"{name}\" xml:space=\"preserve\">");
        let _ = writeln!(out, "    <value>{value}</value>");
        if let Some(category) = comment {
            let _ = writeln!(out, "    <comment>plural category: {category}</comment>");
        }
        out.push_str("  </data>\n");
    }
    out.push_str("</root>\n");
    out
}

/// The fixed ResX preamble every `.resw` carries; the schema is part of the
/// format rather than anything this generator decides.
const RESW_HEADER: &str = r#"<root>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
"#;

#[cfg(test)]
mod tests {
    use super::{resw, strings_xml, xcstrings};

    const PLURAL: &str = "unread = You have { $count ->\n    [one] { NUMBER($count) } unread message\n   *[other] { NUMBER($count) } unread messages\n }.\n";

    fn locale(source: &str) -> crate::i18n::catalog::Locale {
        crate::i18n::catalog::tests::locale("en", source)
    }

    #[test]
    fn apple_gets_positional_specifiers_typed_by_number() {
        let out = xcstrings("en", &[locale("k = { $who } sent { NUMBER($n) }\n")]);
        assert!(out.contains("%2$@ sent %1$lld"), "{out}");
        assert!(out.contains("\"sourceLanguage\": \"en\""), "{out}");
    }

    #[test]
    fn apple_plurals_become_variations() {
        let out = xcstrings("en", &[locale(PLURAL)]);
        assert!(out.contains("\"variations\""), "{out}");
        assert!(out.contains("\"one\""), "{out}");
        assert!(out.contains("You have %1$lld unread message."), "{out}");
    }

    #[test]
    fn android_names_are_identifiers_and_placeholders_are_positional() {
        let out = strings_xml(&locale("chat-error-x = { $who } sent { NUMBER($n) }\n"));
        assert!(
            out.contains("<string name=\"chat_error_x\">%2$s sent %1$d</string>"),
            "{out}"
        );
    }

    #[test]
    fn android_escapes_the_apostrophes_the_copy_is_full_of() {
        let out = strings_xml(&locale("k = Arut can't reach your node\n"));
        assert!(out.contains("Arut can\\'t reach"), "{out}");
    }

    #[test]
    fn android_plurals_become_a_plurals_element() {
        let out = strings_xml(&locale(PLURAL));
        assert!(out.contains("<plurals name=\"unread\">"), "{out}");
        assert!(
            out.contains("<item quantity=\"other\">You have %1$d unread messages.</item>"),
            "{out}"
        );
    }

    #[test]
    fn windows_gets_brace_placeholders_and_one_entry_per_plural_category() {
        let simple = resw(&locale("k = { $who } sent { NUMBER($n) }\n"));
        assert!(simple.contains("<value>{1} sent {0}</value>"), "{simple}");
        let plural = resw(&locale(PLURAL));
        assert!(plural.contains("name=\"unread_one\""), "{plural}");
        assert!(plural.contains("name=\"unread_other\""), "{plural}");
    }

    #[test]
    fn reordered_translations_keep_the_same_native_argument_positions() {
        let english =
            crate::i18n::catalog::tests::locale("en", "k = { $who } sent { NUMBER($n) }\n");
        let french = crate::i18n::catalog::tests::locale("fr", "k = { NUMBER($n) } de { $who }\n");
        assert_eq!(
            english.messages["k"].arguments(),
            french.messages["k"].arguments()
        );
        assert!(strings_xml(&french).contains("%1$d de %2$s"));
        assert!(resw(&french).contains("{0} de {1}"));
        let apple = xcstrings("en", &[english, french]);
        assert!(apple.contains("%2$@ sent %1$lld"));
        assert!(apple.contains("%1$lld de %2$@"));
    }

    #[test]
    fn xml_targets_escape_markup_characters() {
        let source = "k = a & b < c\n";
        assert!(strings_xml(&locale(source)).contains("a &amp; b &lt; c"));
        assert!(resw(&locale(source)).contains("a &amp; b &lt; c"));
    }
}
