//! Generated by `mise run generate` from bindings/ffi/handles.toml. Do not edit.
//!
//! One `#[export] impl` per scope handle: its projection, its typed error as
//! a Fluent id and arguments, its child scopes, its keyed rows and its
//! revision stream. Intents live in `crate::intents`, in a second
//! `#[export] impl` block on the same type.

use crate::ErrorArg;

/// The `ChatClient` scope, as the bindings export it.
pub struct ChatHandle {
    pub(crate) inner: ChatClient,
}

#[export]
impl ChatHandle {
    /// What this scope publishes right now.
    pub fn state(&self) -> ChatState {
        self.inner.state()
    }

    /// The Fluent message id of the current `ChatError`, if there is one.
    pub fn error_key(&self) -> Option<String> {
        self.inner
            .state()
            .error
            .map(|error| error.message_key().to_owned())
    }

    /// The arguments that message interpolates, each under the name it is
    /// selected by, in the order every generated catalog reads them.
    pub fn error_args(&self) -> Vec<ErrorArg> {
        self.inner
            .state()
            .error
            .map(|error| {
                error
                    .message_args()
                    .into_iter()
                    .map(ErrorArg::from)
                    .collect()
            })
            .unwrap_or_default()
    }

    /// The `ComposerHandle` scope under this one.
    pub fn composer(&self) -> ComposerHandle {
        ComposerHandle {
            inner: self.inner.composer(),
        }
    }

    /// The rows after `after_id`, which never change once keyed, so a
    /// surface appends what it does not have.
    pub fn messages_after(&self, after_id: u64) -> Vec<ChatMessage> {
        self.inner.messages_after(after_id)
    }

    /// One revision per change to what this scope publishes. Each
    /// ecosystem receives its own stream idiom (ADR 0021).
    #[ffi_stream(item = u64, mode = "async")]
    pub fn chat_changes(&self) -> Arc<EventSubscription<u64>> {
        subscription(self.inner.changes())
    }
}
