[package]
name = "arut-watch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "1", default-features = false, features = ["sync"] }
futures-lite = { version = "2.6.1", default-features = false, features = ["alloc"] }

[dev-dependencies]
futures-lite = { version = "2.6.1", default-features = false, features = ["std"] }

[lints]
workspace = true
