// Generated by mise run bindings from Rust FFI exports. Do not edit.
import ArutFfi

public typealias AvailabilityHandle = ArutFfi.AvailabilityHandle
public typealias ChatError = ArutFfi.ChatError
public typealias ChatHandle = ArutFfi.ChatHandle
public typealias ChatMessage = ArutFfi.ChatMessage
public typealias ChatRole = ArutFfi.ChatRole
public typealias ChatState = ArutFfi.ChatState
public typealias ChatStatus = ArutFfi.ChatStatus
public typealias ChatSummary = ArutFfi.ChatSummary
public typealias ComposerError = ArutFfi.ComposerError
public typealias ComposerHandle = ArutFfi.ComposerHandle
public typealias ComposerState = ArutFfi.ComposerState
public typealias ComposerStatus = ArutFfi.ComposerStatus
public typealias ConversationsHandle = ArutFfi.ConversationsHandle
public typealias FeatureAvailability = ArutFfi.FeatureAvailability
public typealias HostIds = ArutFfi.HostIds
public typealias NodeFailure = ArutFfi.NodeFailure
public typealias ProductSessionHandle = ArutFfi.ProductSessionHandle
public typealias SessionAvailability = ArutFfi.SessionAvailability

public func createProductSession(pendingScopeId: String) -> ProductSessionHandle {
    ArutFfi.createProductSession(pendingScopeId: pendingScopeId)
}

public func createBrowserSession(pendingScopeId: String, ids: HostIds) -> ProductSessionHandle {
    ArutFfi.createBrowserSession(pendingScopeId: pendingScopeId, ids: ids)
}
