// swift-tools-version: 6.2
//
// Same manifest level as bindings/swift: the Swift 6 language mode, and the
// `@retroactive` conformances in ErrorSources.swift are required rather than
// merely allowed. 6.2 ships with Xcode 26.0.
import PackageDescription

let package = Package(
    name: "ArutSurface",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(name: "ArutSurface", targets: ["ArutSurface"]),
    ],
    dependencies: [
        .package(name: "ArutBindings", path: "../../../bindings/swift"),
    ],
    targets: [
        .target(
            name: "ArutSurface",
            dependencies: [.product(name: "ArutBindings", package: "ArutBindings")],
            // Resources/Localizable.xcstrings is generated by `mise run generate`
            // from product/i18n/locales (ADR 0022).
            resources: [.process("Resources")],
            // A SwiftUI module is main-actor throughout; SE-0466 states that once
            // here instead of on every observable class and every initializer.
            swiftSettings: [.defaultIsolation(MainActor.self)]
        ),
    ]
)
