from pathlib import Path
root = Path(__file__).resolve().parent
outputs = ['swift/Sources/ArutBindings/ObservableState.swift', 'kotlin/src/main/kotlin/dev/arut/bindings/ObservableState.kt', 'typescript/src/observable.ts']
for output in outputs:
    target = root / output
    template = root / "templates" / (target.name + ".in")
    target.write_text("// Generated by bindings/generate-observers.py.\n" + template.read_text())
